-- Update Character Dialogue Master Table
-- This script will replace all existing dialogue entries with the new list

-- First, deactivate all existing entries
UPDATE character_dialogue_master 
SET is_active = false, 
    updated_at = NOW();

-- Insert new dialogue entries
INSERT INTO character_dialogue_master (dialogue_text, dialogue_type, weight, is_active, created_at, updated_at) VALUES
-- General/Motivational Dialogues
('Sharpening my courage… and this butter knife.', 'motivational', 1, true, NOW(), NOW()),
('Discipline is a spell I cast every morning.', 'motivational', 1, true, NOW(), NOW()),
('Quiet steps, loud wins.', 'motivational', 1, true, NOW(), NOW()),
('Hey, partner—guard the calm, I''ll guard the quest.', 'general', 1, true, NOW(), NOW()),
('Every minute I focus, the dragon sneezes a little.', 'motivational', 1, true, NOW(), NOW()),
('Treasure maps are just to-do lists with flair.', 'general', 1, true, NOW(), NOW()),
('One breath in, one task down.', 'motivational', 1, true, NOW(), NOW()),
('XP is just patience wearing a cape.', 'motivational', 1, true, NOW(), NOW()),
('Sparks like these? Earned, not found.', 'achievement', 1, true, NOW(), NOW()),
('I packed snacks and resolve—mostly resolve.', 'general', 1, true, NOW(), NOW()),
('A tidy mind swings straighter than any sword.', 'motivational', 1, true, NOW(), NOW()),
('Today''s boss: distractions. Weak to silence.', 'motivational', 1, true, NOW(), NOW()),
('I''m not tiny—I''m concentrated.', 'motivational', 1, true, NOW(), NOW()),
('Footwork quiet, heartbeat steady.', 'motivational', 1, true, NOW(), NOW()),
('The dungeon of procrastination has endless corridors. I brought a lantern.', 'motivational', 1, true, NOW(), NOW()),
('Discipline is my favorite rare drop.', 'motivational', 1, true, NOW(), NOW()),
('We train small to win big.', 'motivational', 1, true, NOW(), NOW()),
('Another pebble on the path to the peak.', 'motivational', 1, true, NOW(), NOW()),
('Focus first, fireworks later.', 'motivational', 1, true, NOW(), NOW()),
('The dragon fears checkmarks.', 'motivational', 1, true, NOW(), NOW()),
('Steel your will; I''ll steel the dagger.', 'general', 1, true, NOW(), NOW()),
('Routine is just fast travel for progress.', 'motivational', 1, true, NOW(), NOW()),
('Shh—listening for the next right step.', 'motivational', 1, true, NOW(), NOW()),
('Mobs respawn. Momentum shouldn''t.', 'motivational', 1, true, NOW(), NOW()),
('A calm mind is my strongest stat.', 'motivational', 1, true, NOW(), NOW()),
('I can hear the treasure chest clicking ''almost.''', 'achievement', 1, true, NOW(), NOW()),
('Hero tip: bravery looks a lot like finishing.', 'motivational', 1, true, NOW(), NOW()),
('We don''t chase motivation; we schedule it.', 'motivational', 1, true, NOW(), NOW()),
('One quiet session. One louder life.', 'motivational', 1, true, NOW(), NOW()),
('Even dragons blink. That''s our window.', 'motivational', 1, true, NOW(), NOW()),
('Sparks love discipline more than luck.', 'motivational', 1, true, NOW(), NOW()),
('If focus had footsteps, you''d hear marching.', 'motivational', 1, true, NOW(), NOW()),
('Quest log says: do the next small thing.', 'general', 1, true, NOW(), NOW()),
('I polished my shield and my priorities.', 'motivational', 1, true, NOW(), NOW()),
('Adventure begins when excuses end.', 'motivational', 1, true, NOW(), NOW()),
('The map is messy; our steps don''t have to be.', 'motivational', 1, true, NOW(), NOW()),
('Sword in hand, phone asleep—perfect.', 'motivational', 1, true, NOW(), NOW()),
('Tiny heroes take giant minutes.', 'motivational', 1, true, NOW(), NOW()),
('I put bravery on repeat.', 'motivational', 1, true, NOW(), NOW()),
('Progress tastes like warm bread and effort.', 'achievement', 1, true, NOW(), NOW()),
('The dragon whispers ''later''; we answer ''now.''', 'motivational', 1, true, NOW(), NOW()),
('I''m stacking quiet like coins.', 'motivational', 1, true, NOW(), NOW()),
('Discipline isn''t heavy when you lift it daily.', 'motivational', 1, true, NOW(), NOW()),
('We''ll out-focus the flame.', 'motivational', 1, true, NOW(), NOW()),
('I''ll handle the mobs; you handle the stillness.', 'general', 1, true, NOW(), NOW()),
('Patience: the crit hit of real life.', 'motivational', 1, true, NOW(), NOW()),
('I aim my arrows where attention points.', 'motivational', 1, true, NOW(), NOW()),
('The questline of today: start, stick, finish.', 'general', 1, true, NOW(), NOW()),
('Small stride, sure stride, victory stride.', 'motivational', 1, true, NOW(), NOW()),
('Our best loot? Habits we actually use.', 'achievement', 1, true, NOW(), NOW()),
('Eyes on the path, heart on the prize.', 'motivational', 1, true, NOW(), NOW()),
('We''re not just defeating a dragon—we''re becoming the hero who can.', 'motivational', 1, true, NOW(), NOW()),

-- Additional Motivational Dialogues
('Maps can fib; minutes never do.', 'motivational', 1, true, NOW(), NOW()),
('I keep the torch; you keep the hush.', 'general', 1, true, NOW(), NOW()),
('Quiet turns to coins faster than crits.', 'motivational', 1, true, NOW(), NOW()),
('The timer is our drum. March with me.', 'motivational', 1, true, NOW(), NOW()),
('A steady breath beats a shiny sword.', 'motivational', 1, true, NOW(), NOW()),
('Focus is just bravery sitting still.', 'motivational', 1, true, NOW(), NOW()),
('I packed patience, on purpose.', 'motivational', 1, true, NOW(), NOW()),
('Every checkmark is a tiny roar back.', 'achievement', 1, true, NOW(), NOW()),
('Let the phone sleep—let the hero wake.', 'motivational', 1, true, NOW(), NOW()),
('We loot time and forge progress.', 'motivational', 1, true, NOW(), NOW()),
('The path clears when the mind does.', 'motivational', 1, true, NOW(), NOW()),
('Small wins stack like bricks—castle soon.', 'achievement', 1, true, NOW(), NOW()),
('I''m saving my crit for distractions.', 'motivational', 1, true, NOW(), NOW()),
('Lantern bright, excuses light.', 'motivational', 1, true, NOW(), NOW()),
('Grinding XP? More like polishing today.', 'motivational', 1, true, NOW(), NOW()),
('One minute more. That''s the secret door.', 'motivational', 1, true, NOW(), NOW()),
('Focus casts shield on everything else.', 'motivational', 1, true, NOW(), NOW()),
('The calm is our companion.', 'motivational', 1, true, NOW(), NOW()),
('Aim true, even at tiny tasks.', 'motivational', 1, true, NOW(), NOW()),
('Sparks follow footsteps, not wishes.', 'motivational', 1, true, NOW(), NOW()),
('I brought resolve; it fits every dungeon.', 'motivational', 1, true, NOW(), NOW()),
('Silence is my favorite buff.', 'motivational', 1, true, NOW(), NOW()),
('We don''t rush— we repeat.', 'motivational', 1, true, NOW(), NOW()),
('Dragons hate tidy lists.', 'motivational', 1, true, NOW(), NOW()),
('Let the world scroll; we''ll stroll.', 'motivational', 1, true, NOW(), NOW()),
('Mind steady, hands steady, story steady.', 'motivational', 1, true, NOW(), NOW()),
('I''ll guard the quest if you guard the quiet.', 'general', 1, true, NOW(), NOW()),
('Routine is the rope bridge—cross it daily.', 'motivational', 1, true, NOW(), NOW()),
('The treasure is attention, not the chest.', 'motivational', 1, true, NOW(), NOW()),
('Hold the stillness; I''ll hold the line.', 'general', 1, true, NOW(), NOW()),
('Every ''now'' is a secret shortcut.', 'motivational', 1, true, NOW(), NOW()),
('Focus first, flair later.', 'motivational', 1, true, NOW(), NOW()),
('We train the minute, the minute trains us.', 'motivational', 1, true, NOW(), NOW()),
('Turn effort into echo: done, done, done.', 'achievement', 1, true, NOW(), NOW()),
('When I''m ready, the path is ready.', 'motivational', 1, true, NOW(), NOW()),
('Defeat the dragon? Easy—one calm session at a time.', 'motivational', 1, true, NOW(), NOW()),
('I bank quiet like treasure.', 'motivational', 1, true, NOW(), NOW()),
('Eyes forward; feeds can wait.', 'motivational', 1, true, NOW(), NOW()),
('I stack minutes like bricks.', 'motivational', 1, true, NOW(), NOW()),
('Small calm, big crit.', 'motivational', 1, true, NOW(), NOW()),
('Phone asleep, courage awake.', 'motivational', 1, true, NOW(), NOW()),
('Quest log: the next true thing.', 'general', 1, true, NOW(), NOW()),
('I''m guarding your momentum.', 'general', 1, true, NOW(), NOW()),
('Silence is our shortcut.', 'motivational', 1, true, NOW(), NOW()),
('Every kept minute flips a map tile.', 'motivational', 1, true, NOW(), NOW()),
('The dragon fears steady footsteps.', 'motivational', 1, true, NOW(), NOW()),
('Focus is flameproof.', 'motivational', 1, true, NOW(), NOW()),
('Coins jingle louder after quiet.', 'achievement', 1, true, NOW(), NOW()),
('Less scroll, more soul.', 'motivational', 1, true, NOW(), NOW()),
('I''ll farm discipline; you farm stillness.', 'general', 1, true, NOW(), NOW()),
('We polish minutes till they shine.', 'motivational', 1, true, NOW(), NOW()),
('Breathe in, boss out.', 'motivational', 1, true, NOW(), NOW()),
('Calm makes the compass point.', 'motivational', 1, true, NOW(), NOW()),
('We win by inches, not inches per second.', 'motivational', 1, true, NOW(), NOW()),
('Let the horizon load; we''ll move.', 'motivational', 1, true, NOW(), NOW()),
('Today''s potion: patience.', 'motivational', 1, true, NOW(), NOW()),
('Quiet is my favorite mount.', 'motivational', 1, true, NOW(), NOW()),
('I keep watch; you keep hush.', 'general', 1, true, NOW(), NOW()),
('One focused minute beats ten noisy ones.', 'motivational', 1, true, NOW(), NOW()),
('I packed grit and gentle.', 'motivational', 1, true, NOW(), NOW()),
('The chest opens for finishers.', 'achievement', 1, true, NOW(), NOW()),
('Hold the line; I''ll hold the blade.', 'general', 1, true, NOW(), NOW()),
('Minutes are seeds; progress is harvest.', 'motivational', 1, true, NOW(), NOW()),
('Routines are the real relics.', 'motivational', 1, true, NOW(), NOW()),
('We travel at the speed of attention.', 'motivational', 1, true, NOW(), NOW()),
('I''m tiny, not timid.', 'motivational', 1, true, NOW(), NOW()),
('Your stillness is my spell slot.', 'general', 1, true, NOW(), NOW()),
('Let the feed cool; let the forge heat.', 'motivational', 1, true, NOW(), NOW()),
('We don''t chase; we choose.', 'motivational', 1, true, NOW(), NOW()),
('Quiet clicks into place like gear teeth.', 'motivational', 1, true, NOW(), NOW()),
('Aim small, hit true.', 'motivational', 1, true, NOW(), NOW()),
('I''m saving a victory dance for later.', 'motivational', 1, true, NOW(), NOW()),
('The dragon naps on excuses.', 'motivational', 1, true, NOW(), NOW()),
('Maps change; discipline doesn''t.', 'motivational', 1, true, NOW(), NOW()),
('I carry the quest; you carry the calm.', 'general', 1, true, NOW(), NOW()),
('Sharp mind, soft steps.', 'motivational', 1, true, NOW(), NOW()),
('Our best buff? Begin.', 'motivational', 1, true, NOW(), NOW()),
('Scrolls can wait; goals can''t.', 'motivational', 1, true, NOW(), NOW()),
('Hush is heavy armor.', 'motivational', 1, true, NOW(), NOW()),
('One task, one torch.', 'motivational', 1, true, NOW(), NOW()),
('Momentum tastes like warm bread.', 'achievement', 1, true, NOW(), NOW()),
('I polish courage between breaths.', 'motivational', 1, true, NOW(), NOW()),
('The timer is a tiny temple.', 'motivational', 1, true, NOW(), NOW()),
('We''re crafting a habit blade.', 'motivational', 1, true, NOW(), NOW()),
('Hold the quiet; I''ll land the hit.', 'general', 1, true, NOW(), NOW()),
('Boredom is just a boss in disguise.', 'motivational', 1, true, NOW(), NOW()),
('XP grows where attention flows.', 'motivational', 1, true, NOW(), NOW()),
('I''m not idle—I''m aligning.', 'motivational', 1, true, NOW(), NOW()),
('Silence turns minutes into milestones.', 'motivational', 1, true, NOW(), NOW()),
('We make progress at whisper volume.', 'motivational', 1, true, NOW(), NOW()),
('The cave opens to patient feet.', 'motivational', 1, true, NOW(), NOW()),
('I file doubts like dull knives.', 'motivational', 1, true, NOW(), NOW()),
('Let''s build a streak worth bragging to ourselves about.', 'motivational', 1, true, NOW(), NOW()),
('Phone down; visor down.', 'motivational', 1, true, NOW(), NOW()),
('The questline is simple: now → next.', 'general', 1, true, NOW(), NOW()),
('We practice bravery in quiet rooms.', 'motivational', 1, true, NOW(), NOW()),
('I carry your promise like a shield.', 'general', 1, true, NOW(), NOW()),
('Treasure follows tidy choices.', 'motivational', 1, true, NOW(), NOW()),
('We train the minute; the minute trains us.', 'motivational', 1, true, NOW(), NOW()),
('Attention is our rarest drop.', 'motivational', 1, true, NOW(), NOW()),
('I''m farming clarity, one breath at a time.', 'motivational', 1, true, NOW(), NOW()),
('We don''t need luck—just starts.', 'motivational', 1, true, NOW(), NOW()),
('Keep the hush; earn the hush money.', 'motivational', 1, true, NOW(), NOW()),
('Less noise, more notice.', 'motivational', 1, true, NOW(), NOW()),
('Your focus fuels my footsteps.', 'general', 1, true, NOW(), NOW()),
('Even dragons respect schedules.', 'motivational', 1, true, NOW(), NOW()),
('This minute is a doorway; we walk through.', 'motivational', 1, true, NOW(), NOW()),
('I''ll stitch small wins into a banner.', 'achievement', 1, true, NOW(), NOW()),
('Calm hands, clear map.', 'motivational', 1, true, NOW(), NOW()),
('We reroll distraction into direction.', 'motivational', 1, true, NOW(), NOW()),
('One still phone. One loud life.', 'motivational', 1, true, NOW(), NOW()),
('Practice makes peaceful.', 'motivational', 1, true, NOW(), NOW()),
('I''m stockpiling yeses to future you.', 'motivational', 1, true, NOW(), NOW()),
('The hard part is starting; look, we started.', 'motivational', 1, true, NOW(), NOW()),
('We march by metronome, not mood.', 'motivational', 1, true, NOW(), NOW()),
('I keep a lantern in the boring parts.', 'motivational', 1, true, NOW(), NOW()),
('Noise is cheap; results are minted.', 'motivational', 1, true, NOW(), NOW()),
('Focus feels like flying at walking speed.', 'motivational', 1, true, NOW(), NOW()),
('We outlast the scroll.', 'motivational', 1, true, NOW(), NOW()),
('I''m small, but the plan is big.', 'motivational', 1, true, NOW(), NOW()),
('Hold steady—loot''s lighter than regret.', 'motivational', 1, true, NOW(), NOW()),
('We''re closer than the dragon thinks.', 'motivational', 1, true, NOW(), NOW()),
('Stay with me; this minute matters.', 'motivational', 1, true, NOW(), NOW()),
('Quiet now, legend later.', 'motivational', 1, true, NOW(), NOW()),

-- Nature/Outdoor Dialogues
('Touch grass checkpoint—nature says hi.', 'general', 1, true, NOW(), NOW()),
('Fresh air buff applied.', 'achievement', 1, true, NOW(), NOW()),
('Sunshine crits boredom.', 'motivational', 1, true, NOW(), NOW()),
('Feet on ground, mind on quest.', 'motivational', 1, true, NOW(), NOW()),
('Green leaves, clear thoughts.', 'motivational', 1, true, NOW(), NOW()),
('We refill mana outdoors.', 'motivational', 1, true, NOW(), NOW()),
('Clouds are just slow dragons.', 'general', 1, true, NOW(), NOW()),
('The breeze is my party member.', 'general', 1, true, NOW(), NOW()),
('Stretch, sip, step—then we strike.', 'motivational', 1, true, NOW(), NOW()),
('I''ll hold the camp; you touch the grass.', 'general', 1, true, NOW(), NOW()),
('Adventure begins at the door.', 'motivational', 1, true, NOW(), NOW()),
('A short walk is long courage.', 'motivational', 1, true, NOW(), NOW()),
('Trails teach better than feeds.', 'motivational', 1, true, NOW(), NOW()),
('Pebbles count as loot too.', 'achievement', 1, true, NOW(), NOW()),
('We scout the sky, then the dungeon.', 'general', 1, true, NOW(), NOW()),
('Sun patches = save points.', 'achievement', 1, true, NOW(), NOW()),
('Birdsong beats notification pings.', 'motivational', 1, true, NOW(), NOW()),
('Grounded feet, flying focus.', 'motivational', 1, true, NOW(), NOW()),
('Grass under shoes, fire in heart.', 'motivational', 1, true, NOW(), NOW()),
('We earn Sparks; nature earns smiles.', 'achievement', 1, true, NOW(), NOW()),
('Sip water, set timer, set forth.', 'motivational', 1, true, NOW(), NOW()),
('Touch grass; I''ll polish plans.', 'general', 1, true, NOW(), NOW()),
('Outside quests buff inside quests.', 'motivational', 1, true, NOW(), NOW()),
('We don''t doom-scroll; we horizon-scroll.', 'motivational', 1, true, NOW(), NOW()),
('Dragon smoke looks like morning mist.', 'general', 1, true, NOW(), NOW()),
('Discipline is a trail marker.', 'motivational', 1, true, NOW(), NOW()),
('Starlight makes excellent motivation.', 'motivational', 1, true, NOW(), NOW()),
('Wind in cloak, thoughts in order.', 'motivational', 1, true, NOW(), NOW()),
('Your stride sets my pace.', 'general', 1, true, NOW(), NOW()),
('Sunset says: one more calm minute.', 'motivational', 1, true, NOW(), NOW()),
('We farm clarity under open skies.', 'motivational', 1, true, NOW(), NOW()),
('Grass heals brainrot faster than potions.', 'motivational', 1, true, NOW(), NOW()),
('Step outside, then step into focus.', 'motivational', 1, true, NOW(), NOW()),
('Adventure loves comfy shoes.', 'general', 1, true, NOW(), NOW()),
('We don''t chase dragons—we prepare for them.', 'motivational', 1, true, NOW(), NOW()),
('Breath deep; load courage.', 'motivational', 1, true, NOW(), NOW()),
('A patch of green is a tiny arena.', 'motivational', 1, true, NOW(), NOW()),
('Touch bark; tame thoughts.', 'motivational', 1, true, NOW(), NOW()),
('Routines root us like trees.', 'motivational', 1, true, NOW(), NOW()),
('Discipline is trail mix for the mind.', 'motivational', 1, true, NOW(), NOW()),
('Pocket the phone, pocket the win.', 'motivational', 1, true, NOW(), NOW()),
('Quiet paths, loud progress.', 'motivational', 1, true, NOW(), NOW()),
('I log steps as secret side quests.', 'achievement', 1, true, NOW(), NOW()),
('Rain smells like reset.', 'motivational', 1, true, NOW(), NOW()),
('We map the world, then the work.', 'motivational', 1, true, NOW(), NOW()),
('Sky check—then streak check.', 'general', 1, true, NOW(), NOW()),
('Grassproof your goals.', 'motivational', 1, true, NOW(), NOW()),
('We outwalk the algorithm.', 'motivational', 1, true, NOW(), NOW()),
('Sand, stone, soil—choose your buff.', 'motivational', 1, true, NOW(), NOW()),
('Sun on face, grin unlocked.', 'achievement', 1, true, NOW(), NOW()),
('A breeze untangles brain knots.', 'motivational', 1, true, NOW(), NOW()),
('Nature''s patch notes: slow down.', 'motivational', 1, true, NOW(), NOW()),
('Trail ahead; tasks aligned.', 'motivational', 1, true, NOW(), NOW()),
('Fence-sit less; fence-hop dreams.', 'motivational', 1, true, NOW(), NOW()),
('We take the scenic route to discipline.', 'motivational', 1, true, NOW(), NOW()),
('Tiny hero, big outdoors.', 'motivational', 1, true, NOW(), NOW()),
('Hydrate, then dominate.', 'motivational', 1, true, NOW(), NOW()),
('Boots beat bookmarks.', 'motivational', 1, true, NOW(), NOW()),
('The dragon hates sunlight and schedules.', 'motivational', 1, true, NOW(), NOW()),
('We train attention under blue ceilings.', 'motivational', 1, true, NOW(), NOW()),
('Green views, gold rewards.', 'achievement', 1, true, NOW(), NOW()),
('Dirt roads > rabbit holes.', 'motivational', 1, true, NOW(), NOW()),
('Touch grass, then touch greatness.', 'motivational', 1, true, NOW(), NOW()),
('Leaves clap when you show up.', 'achievement', 1, true, NOW(), NOW()),
('Trail dust is just experience glitter.', 'achievement', 1, true, NOW(), NOW()),
('Step count? I track courage count.', 'achievement', 1, true, NOW(), NOW()),
('Calm outside; crits inside.', 'motivational', 1, true, NOW(), NOW()),
('A short stroll beats a long scroll.', 'motivational', 1, true, NOW(), NOW()),
('We plant habits like seeds.', 'motivational', 1, true, NOW(), NOW()),
('Horizon hunting unlocks focus.', 'motivational', 1, true, NOW(), NOW()),
('Sunscreen: armor of the day.', 'general', 1, true, NOW(), NOW()),
('We collect clouds, not tabs.', 'motivational', 1, true, NOW(), NOW()),
('Grass underfoot, dragon underfoot soon.', 'motivational', 1, true, NOW(), NOW()),
('Bench break—then boss fight.', 'motivational', 1, true, NOW(), NOW()),
('Look up, gear up, level up.', 'motivational', 1, true, NOW(), NOW()),
('Touch grass now; torch dungeons later.', 'motivational', 1, true, NOW(), NOW());

-- Verify the update
SELECT COUNT(*) as total_dialogues, 
       COUNT(CASE WHEN is_active = true THEN 1 END) as active_dialogues,
       COUNT(CASE WHEN dialogue_type = 'motivational' THEN 1 END) as motivational_count,
       COUNT(CASE WHEN dialogue_type = 'general' THEN 1 END) as general_count,
       COUNT(CASE WHEN dialogue_type = 'achievement' THEN 1 END) as achievement_count
FROM character_dialogue_master;
